### ISSUE TITLE
Provide API for generic trees

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/trace-server-protocol#19]
Trees are useful for showing aggregations and summaries, such as statistics. The TSP currently doesn't have a generic API for such data structure. 

Things to consider:
- API for trees with columns.
- API to query column descriptors to describe the table column (name/tooltip)
- Align APIs for trees in timegraph, XY etc.

**Comment by bhufmann** [comment]
Pull request #25 introduces a data tree API that is aligned with tree API for XY and Time Graphs.

**Comment by tahini** [comment]
Is this bug fixed?

**Comment by bhufmann** [comment]
> Is this bug fixed?

I think we can close it. I'll remove the alignment of the API with the virtual table from the scope of this issue tracker.
