### ISSUE TITLE
Clarify the 'tags' attributes of some objects

### ISSUE THREAD

**Issue by tahini** [theia-ide/trace-server-protocol#33]
Many model objects have an 'tags' attribute (for example XYSeries, LineMode, and others). The types is often and integer int32, in XYSeries, it's an array of int32.

It's probably related to filters, as the Filter tags description says "Tags to be applied on elements that pass this filter".

- [ ] The description of the attributes should specify that those tags match the filter tags specified.

- [ ] The /filters endpoint should explain the expected mechanic between filters and tags

- [ ] Make sure that the types are OK between int or array of ints

**Comment by bhufmann** [comment]
#54 added a description about Tags and there intention.
