### ISSUE TITLE
Provide 2 TSP specifications for currently supported APIs and proposed APIs

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/trace-server-protocol#61]
Right now the TSP specification contains currently supported and used APIs as well as proposed APIs.
- It's not clear what is actually used and supported and what is a proposal.
- Split the TSP yaml description into 2 files:
> 1. Currently implemented and supported APIs
> 2. Future, proposed APIs (+ APIs of bullet 1)
- Check if https://github.com/swagger-api/swagger-core can be used to automatically generate 1's.

**Comment by marco-miller** [comment]
https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/185637

**Comment by marco-miller** [comment]
- [This other change](https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/185912) aims at stabilizing the earlier 2020-06 version.
- If it ends up working well enough, we may abandon the potentially temporary [revert](https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/185757).

**Comment by marco-miller** [comment]
More [related WIP](https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/186025).
